django_server/authtest/bookmarkmanager/urls.py
from django.conf.urls import patterns, url

from bookmarkmanager import views

urlpatterns = patterns('',
    #url(r'^testpath$', views.testdomain),
    url(r'^$', views.index, name='index'),
    url(r'^sessions/$', views.sessions, name='sessions'),
    url(r'^tags/$', views.tags, name='tags'),
    url(r'^add/$', views.add_bookmark, name='add_bookmark'),
    url(r'^submit/$', views.submit_bookmark, name='submit_bookmark'),
    url(r'^submit/(?P<bookmark_id>\d+)/$', views.update_bookmark, name='update_bookmark'),
    url(r'^edit/(?P<bookmark_id>\d+)/$', views.edit_bookmark, name='edit_bookmark'),
    url(r'^view/(?P<bookmark_id>\d+)/$', views.view_bookmark, name='view_bookmark'),
    url(r'^delete/(?P<bookmark_id>\d+)/$', views.delete_bookmark, name='delete_bookmark'),
    url(r'^add/s/$', views.add_session, name='add_session'),
    url(r'^submit/s/$', views.submit_session, name='submit_session'),
    url(r'^submit/s/(?P<session_id>\d+)/$', views.update_session, name='update_session'),
    url(r'^edit/s/(?P<session_id>\d+)/$', views.edit_session, name='edit_session'),
    url(r'^delete/s/(?P<session_id>\d+)/$', views.delete_session, name='delete_session'),
    url(r'^add/f/$', views.add_folder, name='add_folder'),
    url(r'^submit/f/$', views.submit_folder, name='submit_folder'),
    url(r'^submit/f/(?P<folder_id>\d+)/$', views.update_folder, name='update_folder'),
    url(r'^edit/f/(?P<folder_id>\d+)/$', views.edit_folder, name='edit_folder'),
    url(r'^delete/f/(?P<folder_id>\d+)/$', views.delete_folder, name='delete_folder'),
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'bookmarkmanager/login.html'}, name='login'),
    url(r'^logout/$', views.bm_logout, name='bm_logout'),
)

django_server/authtest/home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
    url(r'^$', views.frontpage ),
)

django_server/authtest/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('home.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('authtest.urls')),
    url(r'^tokentest/', include('tokentest.urls')),
    url(r'^submittest/', include('testmodel.urls')),
    url(r'^sessionssaver/', include('sessionssaver.urls')),
    url(r'^bookmarkmanager/', include('bookmarkmanager.urls', namespace='bookmarkmanager')),
    url(r'^lastfmscrobbler/', include('lastfmscrobbler.urls', namespace='lastfmscrobbler')),
    url(r'^youtubevidlist/', include('youtubevidlist.urls', namespace='youtubevidlist')),
    url(r'^vidlist/', include('youtubevidlist.urls', namespace='vidlist')),
    url(r'^bugtracker/', include('bugtracker.urls', namespace='bugtracker')),
)

django_server/authtest/bookmarkmanager/models.py
#from django.db import models
#from django.contrib.auth.models import User

#from taggit.managers import TaggableManager

#class Bookmark(models.Model):
#    datetime_added = models.DateTimeField(auto_now_add=True)
#    date_added = models.DateField(auto_now_add=True)
#    title = models.CharField(max_length=200)
#    url = models.URLField()
#    description = models.TextField(blank=True,null=True)
#    tags = TaggableManager(blank=True)
#    owner = models.ForeignKey(User, default=1, editable=False)
#    def owned_by(self,user):
#        return self.owner == user


# from django.conf import settings
# from django.db import models
#
# to use in the future
# see https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.OneToOneField
#
#class UserSettings(models.Model):
#    user = models.OneToOneField(settings.AUTH_USER_MODEL)

django_server/authtest/bookmarkmanager/forms.py
from django.forms import ModelForm
from sessionssaver.models import Bookmark, Session, Folder, TestModel

# Create the form class.
class BookmarkForm(ModelForm):
     class Meta:
         model = Bookmark

class SessionForm(ModelForm):
     class Meta:
         model = Session

class FolderForm(ModelForm):
     class Meta:
         model = Folder

class TestModelForm(ModelForm):
     class Meta:
         model = TestModel

django_server/authtest/bookmarkmanager/views.py
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect

from sessionssaver.models import Bookmark, Session, SessionsSaverTag, Folder
from forms import BookmarkForm, SessionForm, FolderForm

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout

from taggit.models import Tag
from django.core.exceptions import ObjectDoesNotExist #might use to detect if tags exist
from django.db.models import Count

import urlparse

def testdomain(request):
    return HttpResponse("path:"+request.path+" path_info:"+request.path_info)


@login_required()
def index(request):
    #fetch tags to filter by from GET request arguments
    if 'removetag' in request.GET and 'tags' in request.GET :
        current_tags = request.GET['tags']
        tags = current_tags.split(",");
        tags = [tag for tag in tags if tag != request.GET['removetag']]
        current_tags = ",".join(tags);
    elif 'tags' in request.GET:
        current_tags = request.GET['tags']
        tags = current_tags.split(",")
    else:
        current_tags = ''
        tags = []

    #exclude bookmarks with tags matching the following tags, unless the tag exists in the GET request
    hidden_tags = ["hidden"]
    hidden_tags = [hidden_tag for hidden_tag in hidden_tags if hidden_tag not in tags]

    base_url = request.get_host()
    
    if 'f' in request.GET and int(request.GET['f']) >= 0:
        if int(request.GET['f']) == 0:
            bookmarks = None;
            folders = Folder.objects.filter(parent_folder__isnull=True) 
            parent_folder = None;
            count = 0; 
        else:
            bookmarks = Bookmark.objects.filter(parent_folder_id=int(request.GET['f']))
            bookmarks = bookmarks.exclude(session__tags__slug__in=hidden_tags).exclude(tags__slug__in=hidden_tags)
            folders = Folder.objects.filter(parent_folder_id=int(request.GET['f'])) 
            parent_folder = Folder.objects.get(id=int(request.GET['f']));
            count = bookmarks.count() 
                     
    elif 's' in request.GET and int(request.GET['s']) >= 1:
        bookmarks = Bookmark.objects.exclude(tags__slug__in=hidden_tags)
        count = bookmarks.filter(session_id=int(request.GET['s'])).count()
        folders = None;
        parent_folder = None;
    else:
        bookmarks = Bookmark.objects.exclude(session__tags__slug__in=hidden_tags).exclude(tags__slug__in=hidden_tags)
        folders = None;
        parent_folder = None;

        for tag in tags:
            bookmarks = bookmarks.filter(tags__slug=tag)
        count = bookmarks.count() 


    if 'page' in request.GET and int(request.GET['page']) >= 1:
        page = int(request.GET['page'])
    else:
        page = 1
    if 'per_page' in request.GET and int(request.GET['per_page']) >= 1:
        per_page = int(request.GET['per_page'])
    else:
        per_page = 10

    page_start = ((page - 1) * per_page)
    page_end = min( page * per_page, count)

    if 'f' in request.GET and int(request.GET['f']) >= 0:
        session = None
        if 'f' in request.GET and int(request.GET['f']) >= 1:
            bookmarks = bookmarks.order_by('-datetime_added')[page_start:page_end]
    elif 's' in request.GET and int(request.GET['s']) >= 1:
        session = Session.objects.get(pk=int(request.GET['s']))
        bookmarks = bookmarks.filter(session_id=int(request.GET['s'])).order_by('-datetime_added')[page_start:page_end]
    else:
        session = None
        bookmarks = bookmarks.order_by('-datetime_added')[page_start:page_end]

    pager_arg_for_folder = ("&f=" + request.GET['f']) if 'f' in request.GET and int(request.GET['f']) >= 0 else ""
    pager_arg_for_session = ("&s=" + request.GET['s']) if not pager_arg_for_folder and 's' in request.GET and int(request.GET['s']) >= 1 else ""
    pager_arg_for_tags = "&tags="+current_tags if tags else ""
    num_pages = int(((count-1)/per_page) + 1)

    pager_first = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page=1&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">1</a>"] if page != 1 else []
    pager_second = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page=2&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">2</a>"] if page > 3 else []
    pager_dotsbefore = [".."] if page > 4 else [] 
    pager_prev = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page="+str(page-1)+"&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">"+str(page-1)+"</a>"] if page > 2 else [] 
    pager_current = [str(page)]
    pager_next = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page="+str(page+1)+"&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">"+str(page+1)+"</a>"] if page < num_pages - 1 else []
    pager_dotsafter = [".."] if page < num_pages - 3 else [] 
    pager_secondlast = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page="+str(num_pages-1)+"&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">"+str(num_pages-1)+"</a>"] if page < num_pages - 2  else []
    pager_last = ["<a href=\"" + reverse('bookmarkmanager:index') + "?page="+str(num_pages)+"&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">"+str(num_pages)+"</a>"] if page < num_pages else []


    pager = pager_first + pager_second + pager_dotsbefore + pager_prev + pager_current + pager_next + pager_dotsafter + pager_secondlast +  pager_last










    #pager = map((lambda x: ("<a href=\"" + reverse('bookmarkmanager:index') + "?page=" + str(x) + "&per_page=" + str(per_page) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags +"\">"+str(x)+"</a>") if x != page else str(x) ),list(range(1, int((count-1)/per_page) + 2, 1)))
    offsets = map((lambda x: ("<a href=\"" + reverse('bookmarkmanager:index') + "?page=1&per_page=" + str(x) + pager_arg_for_folder + pager_arg_for_session + pager_arg_for_tags + "\">"+str(x)+"</a>") if x != per_page else str(x) ),[10,25,50,100])

    #if (page_end > count):
    #    page_end = count
    if 'f' in request.GET and int(request.GET['f']) >= 0:
        template = loader.get_template('bookmarkmanager/folders.html')
    else:
        template = loader.get_template('bookmarkmanager/index.html')
    context = RequestContext(request, {
        'page_start': (page_start + 1),
        'page_end': page_end,
        'page': page,
        'per_page': per_page,
        'pager': pager,
        'offsets': offsets,
        'count': count,
        'bookmarks': bookmarks,
        'base_url': base_url,
        'current_tags': current_tags,
        'tags': [Tag.objects.get(slug=t) for t in tags],
        'session': session,
        'folders': folders,
        'parent_folder': parent_folder,
    })
    return HttpResponse(template.render(context))

@login_required()
def sessions(request):
    if 'removetag' in request.GET and 'tags' in request.GET :
        current_tags = request.GET['tags']
        tags = current_tags.split(",");
        tags = [tag for tag in tags if tag != request.GET['removetag']]
        current_tags = ",".join(tags);
    elif 'tags' in request.GET:
        current_tags = request.GET['tags']
        tags = current_tags.split(",")
    else:
        current_tags = ''
        tags = []

    hidden_tags = ["hidden"]
    hidden_tags = [hidden_tag for hidden_tag in hidden_tags if hidden_tag not in tags]
    sessions = Session.objects.exclude(tags__slug__in=hidden_tags)

    base_url = request.get_host()

    if tags:
        for tag in tags:
            sessions = sessions.filter(tags__slug=tag)

    count = sessions.count()

    if 'page' in request.GET and int(request.GET['page']) >= 1:
        page = int(request.GET['page'])
    else:
        page = 1
    if 'per_page' in request.GET and int(request.GET['per_page']) >= 1:
        per_page = int(request.GET['per_page'])
    else:
        per_page = 10

    page_start = ((page - 1) * per_page)
    page_end = min( page * per_page, count)

    sessions = sessions.order_by('-datetime_added')[page_start:page_end]

    pager_arg_for_tags = "&tags="+current_tags if tags else ""
    num_pages = int(((count-1)/per_page) + 1)

    #pager = map((lambda x: ("<a href=\"" + reverse('bookmarkmanager:sessions') + "?page=" + str(x) + "&per_page=" + str(per_page) + pager_arg_for_tags + "\">"+str(x)+"</a>") if x != page else str(x) ),list(range(1, int((count-1)/per_page) + 2, 1)))

    """
    pager_first = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page=1&per_page=" + str(per_page) + pager_arg_for_tags + "\"><<</a>"] if page != 1 else []
    pager_prev = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page="+str(page-1)+"&per_page=" + str(per_page) + pager_arg_for_tags + "\"><</a>"] if page > 2 else [] 
    pager_current = ["page "+str(page)+" of "+str(num_pages)]
    pager_next = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page="+str(page+1)+"&per_page=" + str(per_page) + pager_arg_for_tags + "\">></a>"] if page < num_pages - 1 else []
    pager_last = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page="+str(num_pages)+"&per_page=" + str(per_page) + pager_arg_for_tags + "\">>></a>"] if page < num_pages else []

    pager = pager_first + pager_prev + pager_next + pager_last
    """

    pager_first = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page=1&per_page=" + str(per_page) + pager_arg_for_tags + "\">1</a>"] if page != 1 else []
    pager_second = ["<a href=\"" + reverse('bookmarkmanager:sessions') + "?page=2&per_page=" + str(per_page) + pager_arg_for_tags + "\">2</a>"] if page > 3 else []
    pager_dotsbefore = [".."] if page > 4 else [] 

django_server/authtest/bookmarkmanager/templates/bookmarkmanager/folders.html
{% extends "bookmarkmanager/base.html" %}
{% load staticfiles %}

{% block title %}{% if parent_folder %}Folder: {{ parent_folder.title}}{% else %}Folders{% endif %} {{ block.super }}{% endblock title %}

{% block main %}
{% if parent_folder %}
        <div>
            <h1>Folder: {{ parent_folder.title }} {% comment %} <a href="{% url 'bookmarkmanager:edit_session' session.id %}"><img src="{% static 'bookmarkmanager/page_white_edit.png' %}"/></a> <a href="{% url 'bookmarkmanager:delete_session' session.id %}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a> {% endcomment %}</h1>
            {% comment %} <div id="session-info">
            {% if session.title %}Added: {{session.datetime_added}}<br/>{% endif %}
            {% if session.notes %}<div class="index-bookmark-notes"><p>{{ session.notes }}</p></div>{% endif %}
            {% if session.tags.all %}
                <span>> 
                {% for tag in session.tags.all %}
                    <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}&s={{session.id}}{% if current_tags %}{{ '&tags='|add:current_tags|add:','|add:tag.slug }}{% else %}{{ '&tags='|add:tag.slug }}{% endif %}">{{ tag.name }}</a>{% if not forloop.last %}, 
{% endif %}
                {% endfor %}
                </span>
            {% endif %}
            </div>{% endcomment %}
        </div>
{% else %}
        <div>
            <h1>Folders</h1>
        </div>
{% endif %}


<div id="rest-of-page">

{% if parent_folder %}
    <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}&f=0{% if current_tags %}{{ '&tags='|add:current_tags }}{% endif %}">Folders</a> > 
    {% for folder in parent_folder.path %}
        <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}&f={{folder.id}}{% if current_tags %}{{ '&tags='|add:current_tags }}{% endif %}">{{ folder.title }}</a>{% if not forloop.last %} > {% endif %}
    {% endfor %}
    <br/><br/>
{% endif %}


<a href="{% url 'bookmarkmanager:add_folder' %}?parent_folder={{ parent_folder.id }}&title=New+Folder">Add Folder</a> <a href="{% url 'bookmarkmanager:add_bookmark' %}?parent_folder={{ parent_folder.id }}&title=New+Bookmark&url=http://example.com">Add Bookmark</a> 

{% if folders %}
    {% if parent_folder %}<h2>Subfolders</h2>{% endif %}
    <ul>
    {% for folder in folders %}
        <li><a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}&f={{folder.id}}{% if current_tags %}{{ '&tags='|add:current_tags }}{% endif %}">{{ folder.title }}</a> <a href="{% url 'bookmarkmanager:edit_folder' folder.id %}"><img src="{% static 'bookmarkmanager/page_white_edit.png' %}"/></a> <a href="{% url 'bookmarkmanager:delete_folder' folder.id %}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a></li>
    {% endfor %}
    </ul>
{% endif %}


{% if count > 0 and bookmarks %}
    <h2>Bookmarks</h2>
    <span class="index-buttons"><input type="button" onClick="$('.index-bookmark-url').toggle()" value="Show/Hide URLs"/><input type="button" onClick="$('.index-bookmark-notes').toggle()" value="Show/Hide Notes"/></span><br/>
    {{ count }} Bookmark{{ count|pluralize }} {% if tags %}{% if session %}including those {% endif %}matching the tag{{ tags|pluralize }}: {% for tag in tags %}{{ tag.name }}<a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}{{ '&tags='|add:current_tags }}{{ '&removetag='|add:tag.slug }}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a>{% if not forloop.last %}, {% endif %}{% endfor %}.{% else %}in Total.{% endif %}  Showing newest ({{ page_start }} to {{ page_end }}).<br/>

    <ul>
    {% for bookmark in bookmarks %}
        <li>
            <div class="index-bookmark-title"><a href="{{ bookmark.url }}">{{ bookmark.title }}</a> <a href="{% url 'bookmarkmanager:edit_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/page_white_edit.png' %}"/></a> <a href="{% url 'bookmarkmanager:delete_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a> <a href="{% url 'bookmarkmanager:view_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/magnifying_glass_alt.png' %}"/></a></div>
            {% if bookmark.url %}<div class="index-bookmark-url">{{ bookmark.url }}</div>{% endif %}
            {% if bookmark.notes %}<div class="index-bookmark-notes"><p>{{ bookmark.notes }}</p></div>{% endif %}
            {% if bookmark.tags.all %}
                <span>> 
                {% for tag in bookmark.tags.all %}
                    <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}{% if current_tags %}{{ '&tags='|add:current_tags|add:','|add:tag.slug }}{% else %}{{ '&tags='|add:tag.slug }}{% endif %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </span>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% autoescape off %}
    <div>Page: {{ pager|join:" | " }}  go to: <form id="go-to-page-form"><input type="text" size="4" name="page"/><input type="hidden" name="per_page" value="{{ per_page }}" />{% if tags %}<input type="hidden" name="tags" value = "{{current_tags}}">{% endif %}{% if session %}<input type="hidden" name="s" value = "{{session.id}}">{% endif %}<input type="submit" value="Go" /></div>
    <div>Offset: {{ offsets|join:" | " }}</div>
    {% endautoescape %}
{% else %}
    {% if parent_folder and parent_folder != 0 %}<p>No bookmarks.</p>{% endif %}
{% endif %}

<script src="{% static 'bookmarkmanager/js/jquery-2.1.4.js'  %}" >
</script>
</div>
{% endblock main %}

django_server/authtest/bookmarkmanager/templates/bookmarkmanager/index.html
{% extends "bookmarkmanager/base.html" %}
{% load staticfiles %}

{% block title %}{% if session %}Session: {{ session.title|default:session.datetime_added}}{% else %}Bookmarks{% endif %} {{ block.super }}{% endblock title %}

{% comment 'this section now moved to base template' %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'bookmarkmanager/css/style.css' %}">
</head>
<body>

<div id="header">
<a href="{% url 'bookmarkmanager:sessions' %}">All Sessions</a>  |  <a href="{% url 'bookmarkmanager:index' %}">All Bookmarks</a>  |  <a href="{% url 'bookmarkmanager:add_bookmark' %}">Add a bookmark</a>  |
{{ "<a href='javascript:(function(){var a=window,b=document,c=encodeURIComponent,d=a.open(\"https://" |add:base_url|safe }}{% url "bookmarkmanager:add_bookmark" %}{{ "?url=\"+c(b.location)+\"&title=\"+c(b.title)+\"&notes=\"+c(a.getSelection()),\"bkmk_popup\",\"left=\"+((a.screenX||a.screenLeft)+10)+\",top=\"+((a.screenY||a.screenTop)+10)+\",height=420px,width=550px,resizable=1,alwaysRaised=1\");a.setTimeout(function(){d.focus()},300)})();'>Bookmarklet</a>" }}  |
<a href="{% url 'bookmarkmanager:bm_logout' %}">Logout</a><br/>
</div>
{% endcomment %}

{% block main %}
{% if session %}
        <div>
            <h1>Session: {{ session.title|default:session.datetime_added}} <a href="{% url 'bookmarkmanager:edit_session' session.id %}"><img src="{% static 'bookmarkmanager/page_white_edit.png' %}"/></a> <a href="{% url 'bookmarkmanager:delete_session' session.id %}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a></h1>
            <div id="session-info">
            {% if session.title %}Added: {{session.datetime_added}}<br/>{% endif %}
            {% if session.notes %}<div class="index-bookmark-notes"><p>{{ session.notes }}</p></div>{% endif %}
            {% if session.tags.all %}
                <span>> 
                {% for tag in session.tags.all %}
                    <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}&s={{session.id}}{% if current_tags %}{{ '&tags='|add:current_tags|add:','|add:tag.slug }}{% else %}{{ '&tags='|add:tag.slug }}{% endif %}">{{ tag.name }}</a>{% if not forloop.last %}, 
{% endif %}
                {% endfor %}
                </span>
            {% endif %}
            </div>
        </div>
{% else %}
        <div>
            <h1>Bookmarks</h1>
        </div>
{% endif %}

<div id="rest-of-page">
{% if count > 0 and bookmarks %}
    <span class="index-buttons"><input type="button" onClick="$('.index-bookmark-url').toggle()" value="Show/Hide URLs"/><input type="button" onClick="$('.index-bookmark-notes').toggle()" value="Show/Hide Notes"/></span><br/>
    {{ count }} Bookmark{{ count|pluralize }} {% if tags %}{% if session %}including those {% endif %}matching the tag{{ tags|pluralize }}: {% for tag in tags %}{{ tag.name }}<a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}{{ '&tags='|add:current_tags }}{{ '&removetag='|add:tag.slug }}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a>{% if not forloop.last %}, {% endif %}{% endfor %}.{% else %}in Total.{% endif %}  Showing newest ({{ page_start }} to {{ page_end }}).<br/>

    <ul>
    {% for bookmark in bookmarks %}
        <li>
            <div class="index-bookmark-title"><a href="{{ bookmark.url }}">{{ bookmark.title }}</a> <a href="{% url 'bookmarkmanager:edit_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/page_white_edit.png' %}"/></a> <a href="{% url 'bookmarkmanager:delete_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/cross.png' %}"/></a> <a href="{% url 'bookmarkmanager:view_bookmark' bookmark.id %}"><img src="{% static 'bookmarkmanager/magnifying_glass_alt.png' %}"/></a></div>
            {% if bookmark.url %}<div class="index-bookmark-url">{{ bookmark.url }}</div>{% endif %}
            {% if bookmark.notes %}<div class="index-bookmark-notes"><p>{{ bookmark.notes }}</p></div>{% endif %}
            {% if bookmark.tags.all %}
                <span>> 
                {% for tag in bookmark.tags.all %}
                    <a href="{% url 'bookmarkmanager:index' %}?page=1&per_page={{per_page}}{% if current_tags %}{{ '&tags='|add:current_tags|add:','|add:tag.slug }}{% else %}{{ '&tags='|add:tag.slug }}{% endif %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </span>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    {% autoescape off %}
    <div>Page: {{ pager|join:" | " }}  go to: <form id="go-to-page-form"><input type="text" size="4" name="page"/><input type="hidden" name="per_page" value="{{ per_page }}" />{% if tags %}<input type="hidden" name="tags" value = "{{current_tags}}">{% endif %}{% if session %}<input type="hidden" name="s" value = "{{session.id}}">{% endif %}<input type="submit" value="Go" /></div>
    <div>Offset: {{ offsets|join:" | " }}</div>
    {% endautoescape %}
{% else %}
    <p>No bookmarks.</p>
{% endif %}

<script src="{% static 'bookmarkmanager/js/jquery-2.1.4.js'  %}" >
</script>
</div>
{% endblock main %}

{% comment 'this section now also moved to base template' %}
</body>
</html>
{% endcomment %}